### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by gaurav3210** [gaurav3210/Bookstore#1]
I want to create a website with the help of Django but facing the issue. can anyone help me in resolving this

**Comment by khdc-me** [comment]
Let's see if I can help you get through this.

First, what is the issue that you're facing?

**Comment by LOC1207** [comment]
Apologies for late reply. Actually i wanted to make login form for my bookstore but i can't able to make it some base.py related error is coming

**Comment by khdc-me** [comment]
> can't able to make it some base.py related error is coming
What's the error? Probably best to just copy and paste it into here.
